### ISSUE TITLE
Exam02 배열, 어레이, 해쉬맵 with 객체지향

### ISSUE THREAD

**Issue by cothis** [cothis/study#3]
```java
package my.exam.ex02;
// 에러나면 수정해주세요!

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * 간단한 배열, 어레이리스트, 해쉬맵 사용법 문제입니다.
 * 간단한 회원을 추가하고 리스트를 조회하는 시스템을 구현중입니다.
 * 악덕 기획자가 아직 저장소(Repository)를 뭘 사용할지 정해주지 않아서
 * 간단한 배열, 어레이리스트, 해쉬맵, 해쉬셋으로 구현해놓으려고 합니다.
 */
public class Exam02 {

    public static void main(String[] args) {

        //given
        String names[] = {"Smith", "Allen", "Ward", "Jones", "Martin", "Blake"};

        ArrayRepo repository = new ArrayRepo();

        //문제 1 : ArrayRepo addMember, findAll method를 완성시키고 반복문을 이용해서 주어진 이름의 사람들을 모두 추가해주세요.
        // - 그 후, findAll method를 이용하여 repository에 담긴 멤버 리스트를 출력해주세요. (toString은 구현되어 있습니다)

        //문제 2 : ListRepo addMember, findAll method를 완성시키고 반복문을 이용해서 주어진 이름의 사람들을 모두 추가해주세요.
        // - repository에 다시 ListRepo 객체를 생성하여 사용해주세요. 이때 에러가 나는 부분이 있으면 변수 선언 부분을 고쳐주세요.
        // - 그 후, findAll method를 이용하여 repository에 담긴 멤버 리스트를 출력해주세요. (toString은 구현되어 있습니다)

        //문제 3 : MapRepo addMember, findAll method를 완성시키고 반복문을 이용해서 주어진 이름의 사람들을 모두 추가해주세요.
        // - 그 후, findAll method를 이용하여 repository에 담긴 멤버 리스트를 출력해주세요. (toString은 구현되어 있습니다)

        //문제 3-1 : SetRepo addMember, findAll ... 동일하게 구현해주세요.

        //문제 4 : 악덕 기획자가 해쉬맵으로 저장소를 선정했습니다. 그러나, 추후 다시 변경될 수도 있다고 하네요. 그리고 현재 멤버 수를 출력하는
        //        기능을 만들어달라고 요청했습니다. 가능하도록 아래 클래스 및 인터페이스의 메소드를 추가해주세요.

        //클래스의 상속구조를 그려보시고, 문제 2에서 만난 에러를 어떻게 고쳤는지 설명해주세요.
        //문제 4에서 기능을 추가하면서 어떤 점을 느꼈는지 설명해주세요.
    }
}

interface Repository {
    void addMember(Member member);
    void findAll();
}

class ArrayRepo implements Repository {

    private Member members[] = new Member[10];
    private int size = 0;

    @Override
    public void addMember(Member member) {

    }

    @Override
    public void findAll() {

    }
}

class ListRepo implements Repository {

    private List<Member> list = new ArrayList<>();

    @Override
    public void addMember(Member member) {

    }

    @Override
    public void findAll() {

    }
}

class MapRepo implements Repository {

    private Map<String, Member> map = new HashMap<>();

    @Override
    public void addMember(Member member) {

    }

    @Override
    public void findAll() {

    }

    public Member findByName() {
        return null;
    }
}

class SetRepo implements Repository {

    private Set<Member> set = new HashSet<>();

    @Override
    public void addMember(Member member) {

    }

    @Override
    public void findAll() {

    }

    public Member findByName() {
        return null;
    }
}

class Member {
    String name;
    int age;

    public Member(String name) {
        this.name = name;
        age = (int)(Math.random() * 15) + 10;
    }

    @Override
    public String toString() {
        return name + "(" + age + "세)";
    }
}
```

**Comment by yidamyeong** [comment]
ghghghghghg

**Comment by xzllxz456** [comment]
HHHHHHHHHHHHHHHHH

**Comment by yidamyeong** [comment]
public class Exam02 {
 public static void main(String[] args) {

     //given
     String names[] = {"Smith", "Allen", "Ward", "Jones", "Martin", "Blake"};

     ArrayRepo repository = new ArrayRepo();
     
   
     //문제 1 : ArrayRepo addMember, findAll method를 완성시키고 반복문을 이용해서 주어진 이름의 사람들을 모두 추가해주세요.
     // - 그 후, 다시 반복문을 이용하여 repository에 담긴 멤버 리스트를 출력해주세요. (toString은 구현되어 있습니다)
     
     for (int i = 0; i < names.length; i++) {
		Member mem = new Member(names[i]);
		repository.addMember(mem);
	 }
     
     repository.findAll();
     
     System.out.println("--------------");
     
     
     //문제 2 : ListRepo addMember, findAll method를 완성시키고 반복문을 이용해서 주어진 이름의 사람들을 모두 추가해주세요.
     // - repository에 다시 ListRepo 객체를 생성하여 사용해주세요. 이때 에러가 나는 부분이 있으면 변수 선언 부분을 고쳐주세요.
     // - 그 후, 다시 반복문을 이용하여 repository에 담긴 멤버 리스트를 출력해주세요. (toString은 구현되어 있습니다)
     
     ListRepo lr = new ListRepo();
     
     for (int i = 0; i < names.length; i++) {
		lr.addMember(repository.getMembers(i));
     }
     
     lr.findAll();
     
     System.out.println("--------------");
     
     
     //문제 3 : MapRepo addMember, findAll method를 완성시키고 반복문을 이용해서 주어진 이름의 사람들을 모두 추가해주세요.
     // - 그 후, 다시 반복문을 이용하여 repository에 담긴 멤버 리스트를 출력해주세요. (toString은 구현되어 있습니다)
     
     MapRepo mr = new MapRepo();
     
     for (int i = 0; i < names.length; i++) {
		mr.addMember(repository.getMembers(i));
     }
     
     mr.findAll(); 
     
     System.out.println("--------------");
     
     
     //문제 4 : 악덕 기획자가 해쉬맵으로 저장소를 선정했습니다. 그러나, 추후 다시 변경될 수도 있다고 하네요. 그리고 현재 멤버 수를 출력하는
     //        기능을 만들어달라고 요청했습니다. 가능하도록 아래 클래스 및 인터페이스의 메소드를 추가해주세요.
     
     mr.countMembers();
     Member m = mr.findByName();
     System.out.println(m.toString());
     
     
     //클래스의 상속구조를 그려보시고, 문제 2에서 만난 에러를 어떻게 고쳤는지 설명해주세요.
     //문제 4에서 기능을 추가하면서 어떤 점을 느꼈는지 설명해주세요.
 }
}

interface Repository {
 void addMember(Member member);
 void findAll();
 void countMembers();
}

class ArrayRepo implements Repository {

 private Member members[] = new Member[10];
 private int size = 0;

 public Member getMembers(int n) {
	return members[n];
}

@Override
 public void addMember(Member member) {
	 for (int i = 0; i < members.length; i++) {
		if(members[i] == null) {
			members[i] = member;
			size = size + 1;
			break;
		}
	}
	 
 }

 @Override
 public void findAll() {
	 for (int i = 0; i < size; i++) {
		 System.out.println(members[i].toString());
	}
 }

@Override
public void countMembers() {
	System.out.println(size + " Members");
	
}
}


class ListRepo implements Repository {

 private List<Member> list = new ArrayList<>();
 

@Override
 public void addMember(Member member) {
	 list.add(member);
 }

 @Override
 public void findAll() {
	 for (int i = 0; i < list.size(); i++) {
		System.out.println(list.get(i).toString());
	}
 }

@Override
public void countMembers() {
	System.out.println(list.size() + " Members");
	
}
}

class MapRepo implements Repository {
 Scanner sc = new Scanner(System.in);
	
 private Map<String, Member> map = new HashMap<>();

 @Override
 public void addMember(Member member) {
	 map.put(map.size() + "", member);
 }
 
 
 @Override
 public void findAll() {
	 for (int i = 0; i < map.size(); i++) {
		System.out.println(map.get(i + ""));
	}
 }

 public Member findByName() {
     System.out.print("검색할 이름 입력> ");
     String str = sc.next();
     
     int index = -1;
	 for (int i = 0; i < map.size(); i++) {
		if(str.equals(map.get(i + "").name)) {
			index = i;
		}
	 }
	 
	 return map.get(index + "");
 }


@Override
public void countMembers() {
	System.out.println(map.size() + " Members");
	
}
}

class Member {
 String name;
 int age;

 public Member(String name) {
     this.name = name;
     age = (int)(Math.random() * 15) + 10;
 }

 @Override
 public String toString() {
     return name + "(" + age + "세)";
 }
}

**Comment by yidamyeong** [comment]
public class Exam02 {

 public static void main(String[] args) {

     //given
     String names[] = {"Smith", "Allen", "Ward", "Jones", "Martin", "Blake"};

     Repository repository = new ArrayRepo();
     
   
     //문제 1 : ArrayRepo addMember, findAll method를 완성시키고 반복문을 이용해서 주어진 이름의 사람들을 모두 추가해주세요.
     // - 그 후, 다시 반복문을 이용하여 repository에 담긴 멤버 리스트를 출력해주세요. (toString은 구현되어 있습니다)
     
     for (int i = 0; i < names.length; i++) {
		Member member = new Member(names[i]);
		repository.addMember(member);
	 }
     
     repository.findAll();
     
     System.out.println("--------------");
     
     
     //문제 2 : ListRepo addMember, findAll method를 완성시키고 반복문을 이용해서 주어진 이름의 사람들을 모두 추가해주세요.
     // - repository에 다시 ListRepo 객체를 생성하여 사용해주세요. 이때 에러가 나는 부분이 있으면 변수 선언 부분을 고쳐주세요.
     // - 그 후, 다시 반복문을 이용하여 repository에 담긴 멤버 리스트를 출력해주세요. (toString은 구현되어 있습니다)
     
     repository = new ListRepo();
          
     for (int i = 0; i < names.length; i++) {
    	 Member member = new Member(names[i]);
    	 repository.addMember(member);
     }
     
     repository.findAll();
     
     System.out.println("--------------");
     
     
     //문제 3 : MapRepo addMember, findAll method를 완성시키고 반복문을 이용해서 주어진 이름의 사람들을 모두 추가해주세요.
     // - 그 후, 다시 반복문을 이용하여 repository에 담긴 멤버 리스트를 출력해주세요. (toString은 구현되어 있습니다)
     
     repository = new MapRepo();
          
     for (int i = 0; i < names.length; i++) {
		Member member = new Member(names[i]);
    	repository.addMember(member);
     }
     
     repository.findAll(); 
     
     System.out.println("--------------");
     
     
     //문제 4 : 악덕 기획자가 해쉬맵으로 저장소를 선정했습니다. 그러나, 추후 다시 변경될 수도 있다고 하네요. 그리고 현재 멤버 수를 출력하는
     //        기능을 만들어달라고 요청했습니다. 가능하도록 아래 클래스 및 인터페이스의 메소드를 추가해주세요.
     
     repository.countMembers();
     
     MapRepo mr = (MapRepo)repository;
     Member member = mr.findByName();
     System.out.println(member.toString());
     
     
     //클래스의 상속구조를 그려보시고, 문제 2에서 만난 에러를 어떻게 고쳤는지 설명해주세요.
     //문제 4에서 기능을 추가하면서 어떤 점을 느꼈는지 설명해주세요.
 }
}

interface Repository {
 void addMember(Member member);
 void findAll();
 void countMembers();
}

class ArrayRepo implements Repository {

 private Member members[] = new Member[10];
 private int size = 0;

 public Member getMembers(int n) {
	return members[n];
}

@Override
 public void addMember(Member member) {
	 for (int i = 0; i < members.length; i++) {
		if(members[i] == null) {
			members[i] = member;
			size = size + 1;
			break;
		}
	}
	 
 }

 @Override
 public void findAll() {
	 for (int i = 0; i < size; i++) {
		 System.out.println(members[i].toString());
	}
 }

@Override
public void countMembers() {
	System.out.println(size + " Members");
	
}
}


class ListRepo implements Repository {

 private List<Member> list = new ArrayList<>();
 

@Override
 public void addMember(Member member) {
	 list.add(member);
 }

 @Override
 public void findAll() {
	 for (int i = 0; i < list.size(); i++) {
		System.out.println(list.get(i).toString());
	}
 }

@Override
public void countMembers() {
	System.out.println(list.size() + " Members");
	
}
}

class MapRepo implements Repository {
 Scanner sc = new Scanner(System.in);
	
 private Map<String, Member> map = new HashMap<>();

 @Override
 public void addMember(Member member) {
	 map.put(member.name, member);
 }
 
 
 @Override
 public void findAll() {
	for (String key : map.keySet()) {
		System.out.println(map.get(key).toString());
	}
 }

 public Member findByName() {
     System.out.print("검색할 이름 입력> ");
     String name = sc.next();
    	 
	 return map.get(name);
 }


@Override
public void countMembers() {
	System.out.println(map.size() + " Members");
	
}
}

class Member {
 String name;
 int age;

 public Member(String name) {
     this.name = name;
     age = (int)(Math.random() * 15) + 10;
 }

 @Override
 public String toString() {
     return name + "(" + age + "세)";
 }
}

**Comment by yidamyeong** [comment]
```java
public class Exam02 {

 public static void main(String[] args) {

     //given
     String names[] = {"Smith", "Allen", "Ward", "Jones", "Martin", "Blake"};

     Repository repository = new ArrayRepo();
     
   
     //문제 1 : ArrayRepo addMember, findAll method를 완성시키고 반복문을 이용해서 주어진 이름의 사람들을 모두 추가해주세요.
     // - 그 후, 다시 반복문을 이용하여 repository에 담긴 멤버 리스트를 출력해주세요. (toString은 구현되어 있습니다)
     
     for (int i = 0; i < names.length; i++) {
		Member member = new Member(names[i]);
		repository.addMember(member);
	 }
     
     repository.findAll();
     
     System.out.println("--------------");
     
     
     //문제 2 : ListRepo addMember, findAll method를 완성시키고 반복문을 이용해서 주어진 이름의 사람들을 모두 추가해주세요.
     // - repository에 다시 ListRepo 객체를 생성하여 사용해주세요. 이때 에러가 나는 부분이 있으면 변수 선언 부분을 고쳐주세요.
     // - 그 후, 다시 반복문을 이용하여 repository에 담긴 멤버 리스트를 출력해주세요. (toString은 구현되어 있습니다)
     
     repository = new ListRepo();
          
     for (int i = 0; i < names.length; i++) {
    	 Member member = new Member(names[i]);
    	 repository.addMember(member);
     }
     
     repository.findAll();
     
     System.out.println("--------------");
     
     
     //문제 3 : MapRepo addMember, findAll method를 완성시키고 반복문을 이용해서 주어진 이름의 사람들을 모두 추가해주세요.
     // - 그 후, 다시 반복문을 이용하여 repository에 담긴 멤버 리스트를 출력해주세요. (toString은 구현되어 있습니다)
     
     repository = new MapRepo();
          
     for (int i = 0; i < names.length; i++) {
		Member member = new Member(names[i]);
    	repository.addMember(member);
     }
     
     repository.findAll(); 
     
     System.out.println("--------------");
     
     
     //문제 4 : 악덕 기획자가 해쉬맵으로 저장소를 선정했습니다. 그러나, 추후 다시 변경될 수도 있다고 하네요. 그리고 현재 멤버 수를 출력하는
     //        기능을 만들어달라고 요청했습니다. 가능하도록 아래 클래스 및 인터페이스의 메소드를 추가해주세요.
     
     repository.countMembers();
     
     MapRepo mr = (MapRepo)repository;
     Member member = mr.findByName();
     System.out.println(member.toString());
     
     
     //클래스의 상속구조를 그려보시고, 문제 2에서 만난 에러를 어떻게 고쳤는지 설명해주세요.
     //문제 4에서 기능을 추가하면서 어떤 점을 느꼈는지 설명해주세요.
 }
}
```

```java
interface Repository {
 void addMember(Member member);
 void findAll();
 void countMembers();
}
```

```java
class ArrayRepo implements Repository {

 private Member members[] = new Member[10];
 private int size = 0;

 public Member getMembers(int n) {
	return members[n];
}

@Override
 public void addMember(Member member) {
	 for (int i = 0; i < members.length; i++) {
		if(members[i] == null) {
			members[i] = member;
			size = size + 1;
			break;
		}
	}
	 
 }

 @Override
 public void findAll() {
	 for (int i = 0; i < size; i++) {
		 System.out.println(members[i].toString());
	}
 }

@Override
public void countMembers() {
	System.out.println(size + " Members");
	
}
}
```

```java
class ListRepo implements Repository {

 private List<Member> list = new ArrayList<>();
 

@Override
 public void addMember(Member member) {
	 list.add(member);
 }

 @Override
 public void findAll() {
	 for (int i = 0; i < list.size(); i++) {
		System.out.println(list.get(i).toString());
	}
 }

@Override
public void countMembers() {
	System.out.println(list.size() + " Members");
	
}
}
```

```java
class MapRepo implements Repository {
 Scanner sc = new Scanner(System.in);
	
 private Map<String, Member> map = new HashMap<>();

 @Override
 public void addMember(Member member) {
	 map.put(member.name, member);
 }
 
 
 @Override
 public void findAll() {
	for (String key : map.keySet()) {
		System.out.println(map.get(key).toString());
	}
 }

 public Member findByName() {
     System.out.print("검색할 이름 입력> ");
     String name = sc.next();
    	 
	 return map.get(name);
 }


@Override
public void countMembers() {
	System.out.println(map.size() + " Members");
	
}
}
```

```java
class Member {
 String name;
 int age;

 public Member(String name) {
     this.name = name;
     age = (int)(Math.random() * 15) + 10;
 }

 @Override
 public String toString() {
     return name + "(" + age + "세)";
 }
}
```
